" pathogen
call pathogen#infect()
call pathogen#helptags()

" COLORS
syntax on
set background=dark
colorscheme solarized

" GENERAL
set autoindent
set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4

" line numbers
set number

" automatically remove trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" white space, line endings
set list listchars=tab:»·,trail:·

" MAPPINGS
let mapleader = ","

nnoremap <silent> <Leader>f :CommandT<CR>

nmap <Leader>tt :tabnew <CR><Leader>f
nmap <Leader>tc :tabclose<CR>
nmap <Leader>to :tabonly<CR>
nmap <Leader>tn :tabnext<CR>
nmap <Leader>tp :tabprevious<CR>
nmap <Leader>tf :tabfirst<CR>
nmap <Leader>tl :tablast<CR>
nmap <Leader>tm :tabmove



" GUI STUFF
if has('gui_running')
    set guioptions-=T
    set guifont=Andale\ Mono:h12
endif
